version: "3"
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lk-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - load-kmz-network

  #Nginx Service
  lk-server:
    image: nginx:alpine
    container_name: lk-server
    restart: unless-stopped
    tty: true
    # ports:
    #   - "80:80"
    #   - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - load-kmz-network
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.load-kmz.entrypoints=http"
      - "traefik.http.routers.load-kmz.rule=Host(`load-kmz.cekingx.xyz`)"
      - "traefik.http.middlewares.load-kmz-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.load-kmz.middlewares=load-kmz-https-redirect"
      - "traefik.http.routers.load-kmz-secure.entrypoints=https"
      - "traefik.http.routers.load-kmz-secure.rule=Host(`load-kmz.cekingx.xyz`)"
      - "traefik.http.routers.load-kmz-secure.tls=true"
      - "traefik.http.routers.load-kmz-secure.tls.certresolver=http"
      - "traefik.http.routers.load-kmz-secure.service=load-kmz"
      - "traefik.http.services.load-kmz.loadbalancer.server.port=9001"
      - "traefik.docker.network=proxy"

#Docker Networks
networks:
  load-kmz-network:
    driver: bridge
  proxy:
    external: true
